package com.questua.app.presentation.admin.content.questpoints

import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Image
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.questua.app.core.common.URIPathHelper
import com.questua.app.core.ui.components.QuestuaTextField
import com.questua.app.domain.model.City
import com.questua.app.domain.model.QuestPoint
import com.questua.app.domain.model.UnlockRequirement
import java.io.File

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun QuestPointFormDialog(
    questPoint: QuestPoint? = null,
    cities: List<City>,
    onDismiss: () -> Unit,
    onConfirm: (
        title: String, cityId: String, desc: String, difficulty: Int,
        lat: Double, lon: Double, img: File?, icon: File?,
        unlock: UnlockRequirement?, isPremium: Boolean, isAi: Boolean, isPub: Boolean
    ) -> Unit
) {
    val context = LocalContext.current

    // Estados Básicos
    var title by remember { mutableStateOf(questPoint?.title ?: "") }
    var description by remember { mutableStateOf(questPoint?.description ?: "") }
    var cityId by remember { mutableStateOf(questPoint?.cityId ?: "") }
    var difficulty by remember { mutableStateOf(questPoint?.difficulty?.toFloat() ?: 1f) }

    // Localização
    var lat by remember { mutableStateOf(questPoint?.lat?.toString() ?: "") }
    var lon by remember { mutableStateOf(questPoint?.lon?.toString() ?: "") }

    // Arquivos
    var selectedImageFile by remember { mutableStateOf<File?>(null) }
    var selectedIconFile by remember { mutableStateOf<File?>(null) }

    // Flags
    var isPremium by remember { mutableStateOf(questPoint?.isPremium ?: false) }
    var isPublished by remember { mutableStateOf(questPoint?.isPublished ?: true) }
    var isAiGenerated by remember { mutableStateOf(questPoint?.isAiGenerated ?: false) }

    // Requisitos de Desbloqueio
    var reqPremium by remember { mutableStateOf(questPoint?.unlockRequirement?.premiumAccess ?: false) }
    var reqLevel by remember { mutableStateOf(questPoint?.unlockRequirement?.requiredGamificationLevel?.toString() ?: "") }
    var reqCefr by remember { mutableStateOf(questPoint?.unlockRequirement?.requiredCefrLevel ?: "") }

    // Controle do Seletor de Cidade
    var showCityPicker by remember { mutableStateOf(false) }

    // Launchers de Imagem
    val imagePicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let { selectedImageFile = URIPathHelper.getFileFromUri(context, it) }
    }
    val iconPicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let { selectedIconFile = URIPathHelper.getFileFromUri(context, it) }
    }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text(if (questPoint == null) "Novo Ponto" else "Editar Ponto") },
        text = {
            Column(
                Modifier
                    .fillMaxWidth()
                    .verticalScroll(rememberScrollState()),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                QuestuaTextField(value = title, onValueChange = { title = it }, label = "Título do Ponto")

                // SELETOR DE CIDADE (Foreign Key)
                OutlinedCard(onClick = { showCityPicker = true }) {
                    val currentCity = cities.find { it.id == cityId }
                    ListItem(
                        headlineContent = { Text(currentCity?.name ?: "Selecionar Cidade") },
                        supportingContent = { Text(if(cityId.isEmpty()) "Obrigatório" else "ID: $cityId") },
                        colors = ListItemDefaults.colors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
                    )
                }

                QuestuaTextField(value = description, onValueChange = { description = it }, label = "Descrição")

                // Dificuldade
                Column {
                    Text("Dificuldade: ${difficulty.toInt()}", style = MaterialTheme.typography.labelMedium)
                    Slider(
                        value = difficulty,
                        onValueChange = { difficulty = it },
                        valueRange = 1f..5f,
                        steps = 3
                    )
                }

                // Imagens
                Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    Button(onClick = { imagePicker.launch("image/*") }, modifier = Modifier.weight(1f)) {
                        Icon(Icons.Default.Image, null); Spacer(Modifier.width(4.dp))
                        Text(if(selectedImageFile != null) "Img OK" else "Imagem")
                    }
                    Button(onClick = { iconPicker.launch("image/*") }, modifier = Modifier.weight(1f)) {
                        Icon(Icons.Default.Image, null); Spacer(Modifier.width(4.dp))
                        Text(if(selectedIconFile != null) "Icon OK" else "Ícone")
                    }
                }

                Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    QuestuaTextField(value = lat, onValueChange = { lat = it }, label = "Latitude", modifier = Modifier.weight(1f))
                    QuestuaTextField(value = lon, onValueChange = { lon = it }, label = "Longitude", modifier = Modifier.weight(1f))
                }

                HorizontalDivider()
                Text("Requisitos de Desbloqueio", style = MaterialTheme.typography.titleSmall, fontWeight = FontWeight.Bold)

                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = reqPremium, onCheckedChange = { reqPremium = it })
                    Text("Exigir Premium")
                }

                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    QuestuaTextField(value = reqLevel, onValueChange = { reqLevel = it }, label = "Nível Min.", modifier = Modifier.weight(1f))
                    QuestuaTextField(value = reqCefr, onValueChange = { reqCefr = it }, label = "CEFR (Ex: A1)", modifier = Modifier.weight(1f))
                }

                HorizontalDivider()

                Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.SpaceBetween, modifier = Modifier.fillMaxWidth()) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Checkbox(checked = isPublished, onCheckedChange = { isPublished = it })
                        Text("Publicado")
                    }
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Checkbox(checked = isPremium, onCheckedChange = { isPremium = it })
                        Text("Conteúdo Premium")
                    }
                }
            }
        },
        confirmButton = {
            Button(
                onClick = {
                    val unlock = UnlockRequirement(
                        premiumAccess = reqPremium,
                        requiredGamificationLevel = reqLevel.toIntOrNull(),
                        requiredCefrLevel = reqCefr.ifEmpty { null }
                    )
                    onConfirm(
                        title, cityId, description, difficulty.toInt(),
                        lat.toDoubleOrNull() ?: 0.0, lon.toDoubleOrNull() ?: 0.0,
                        selectedImageFile, selectedIconFile,
                        unlock, isPremium, isAiGenerated, isPublished
                    )
                },
                enabled = title.isNotBlank() && cityId.isNotBlank()
            ) { Text("Confirmar") }
        },
        dismissButton = { TextButton(onClick = onDismiss) { Text("Cancelar") } }
    )

    // Dialog de Seleção de Cidade
    if (showCityPicker) {
        AlertDialog(
            onDismissRequest = { showCityPicker = false },
            title = { Text("Selecione a Cidade") },
            text = {
                Box(Modifier.heightIn(max = 400.dp)) {
                    LazyColumn {
                        items(cities) { city ->
                            ListItem(
                                modifier = Modifier.clickable {
                                    cityId = city.id
                                    showCityPicker = false
                                },
                                headlineContent = { Text(city.name) },
                                supportingContent = { Text(city.countryCode) }
                            )
                            HorizontalDivider()
                        }
                    }
                }
            },
            confirmButton = { TextButton(onClick = { showCityPicker = false }) { Text("Fechar") } }
        )
    }
}