package com.questua.app.presentation.admin.content.characters

import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Image
import androidx.compose.material.icons.filled.Mic
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.questua.app.core.common.URIPathHelper
import com.questua.app.core.ui.components.QuestuaTextField
import com.questua.app.domain.model.CharacterEntity
import com.questua.app.domain.model.Persona
import com.questua.app.presentation.admin.content.dialogues.ExpandableListSection
import com.questua.app.presentation.admin.content.dialogues.MediaPickerField
import com.questua.app.presentation.admin.content.dialogues.SectionTitle
import java.io.File

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CharacterFormDialog(
    character: CharacterEntity? = null,
    onDismiss: () -> Unit,
    onConfirm: (
        name: String, avatar: Any?, voice: Any?,
        sprites: List<Any>,
        persona: Persona?, isAi: Boolean
    ) -> Unit
) {
    val context = LocalContext.current

    // Básico
    var name by remember { mutableStateOf(character?.name ?: "") }
    var isAiGenerated by remember { mutableStateOf(character?.isAiGenerated ?: false) }

    // Mídia (Any? pode ser String(Url) ou File)
    var avatar by remember { mutableStateOf<Any?>(character?.avatarUrl) }
    var voice by remember { mutableStateOf<Any?>(character?.voiceUrl) }

    // SpriteSheet (Lista mista)
    val spriteUrls = remember { mutableStateListOf<Any>().apply { addAll(character?.spriteSheet?.urls ?: emptyList()) } }

    // Persona
    var pDesc by remember { mutableStateOf(character?.persona?.description ?: "") }
    var pStyle by remember { mutableStateOf(character?.persona?.speakingStyle ?: "") }
    var pTone by remember { mutableStateOf(character?.persona?.voiceTone ?: "") }
    var pBack by remember { mutableStateOf(character?.persona?.background ?: "") }
    val pTraits = remember { mutableStateListOf<String>().apply { addAll(character?.persona?.traits ?: emptyList()) } }

    // Launchers
    val avatarPicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let { avatar = URIPathHelper.getFileFromUri(context, it) }
    }
    val voicePicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let { voice = URIPathHelper.getFileFromUri(context, it) }
    }
    val spritePicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let { URIPathHelper.getFileFromUri(context, it)?.let { file -> spriteUrls.add(file) } }
    }

    AlertDialog(
        onDismissRequest = onDismiss,
        containerColor = MaterialTheme.colorScheme.surface,
        title = { Text(if (character == null) "Novo Personagem" else "Editar Personagem", fontWeight = FontWeight.Bold) },
        text = {
            Column(
                Modifier
                    .fillMaxWidth()
                    .verticalScroll(rememberScrollState()),
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                // --- INFO BÁSICA ---
                SectionTitle("Informações Básicas")
                QuestuaTextField(value = name, onValueChange = { name = it }, label = "Nome do Personagem")

                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(
                        checked = isAiGenerated,
                        onCheckedChange = { isAiGenerated = it },
                        colors = CheckboxDefaults.colors(checkedColor = QuestuaGold, checkmarkColor = Color.Black)
                    )
                    Text("Gerado por IA")
                }

                // --- ASSETS ---
                SectionTitle("Assets & Mídia")

                // Avatar
                MediaPickerField(
                    label = "Avatar (Imagem)",
                    value = avatar,
                    icon = Icons.Default.Image,
                    onPick = { avatarPicker.launch("image/*") },
                    onClear = { avatar = null }
                )

                // Voice
                MediaPickerField(
                    label = "Voz (Áudio)",
                    value = voice,
                    icon = Icons.Default.Mic,
                    onPick = { voicePicker.launch("audio/*") },
                    onClear = { voice = null }
                )

                // Sprite Sheet List
                ExpandableListSection(title = "Sprite Sheet (${spriteUrls.size})", onAdd = { spritePicker.launch("image/*") }) {
                    spriteUrls.forEachIndexed { index, item ->
                        Row(
                            Modifier
                                .fillMaxWidth()
                                .padding(4.dp)
                                .border(1.dp, MaterialTheme.colorScheme.outlineVariant, RoundedCornerShape(8.dp))
                                .padding(8.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(
                                if(item is File) "Arquivo: ${item.name.take(15)}..." else "URL: ${(item as String).takeLast(15)}",
                                style = MaterialTheme.typography.bodySmall,
                                modifier = Modifier.weight(1f),
                                color = MaterialTheme.colorScheme.onSurface
                            )
                            IconButton(onClick = { spriteUrls.removeAt(index) }, modifier = Modifier.size(24.dp)) {
                                Icon(Icons.Default.Delete, null, tint = MaterialTheme.colorScheme.error)
                            }
                        }
                    }
                }

                HorizontalDivider(color = MaterialTheme.colorScheme.outlineVariant)

                // --- PERSONA ---
                SectionTitle("Persona")
                QuestuaTextField(value = pDesc, onValueChange = { pDesc = it }, label = "Descrição")
                QuestuaTextField(value = pBack, onValueChange = { pBack = it }, label = "Background / História")

                Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    Box(Modifier.weight(1f)) { QuestuaTextField(value = pStyle, onValueChange = { pStyle = it }, label = "Estilo de Fala") }
                    Box(Modifier.weight(1f)) { QuestuaTextField(value = pTone, onValueChange = { pTone = it }, label = "Tom de Voz") }
                }

                // Traits List
                ExpandableListSection(title = "Traços de Personalidade (${pTraits.size})", onAdd = { pTraits.add("") }) {
                    pTraits.forEachIndexed { index, trait ->
                        Row(Modifier.padding(vertical = 4.dp), verticalAlignment = Alignment.CenterVertically) {
                            QuestuaTextField(value = trait, onValueChange = { pTraits[index] = it }, label = "Traço ${index + 1}", modifier = Modifier.weight(1f))
                            IconButton(onClick = { pTraits.removeAt(index) }) {
                                Icon(Icons.Default.Delete, null, tint = MaterialTheme.colorScheme.error)
                            }
                        }
                    }
                }
            }
        },
        confirmButton = {
            Button(
                onClick = {
                    val finalPersona = if (pDesc.isBlank() && pTraits.isEmpty()) null else Persona(
                        description = pDesc.ifBlank { null },
                        traits = pTraits.filter { it.isNotBlank() },
                        speakingStyle = pStyle.ifBlank { null },
                        voiceTone = pTone.ifBlank { null },
                        background = pBack.ifBlank { null }
                    )
                    onConfirm(name, avatar, voice, spriteUrls, finalPersona, isAiGenerated)
                },
                enabled = name.isNotBlank() && (avatar != null),
                colors = ButtonDefaults.buttonColors(containerColor = QuestuaGold, contentColor = Color.Black)
            ) { Text("Salvar", fontWeight = FontWeight.Bold) }
        },
        dismissButton = {
            TextButton(
                onClick = onDismiss,
                colors = ButtonDefaults.textButtonColors(contentColor = MaterialTheme.colorScheme.onSurface)
            ) { Text("Cancelar") }
        },
        shape = RoundedCornerShape(24.dp)
    )
}