package com.questua.app.presentation.admin.content.characters

import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Upload
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.questua.app.core.common.URIPathHelper
import com.questua.app.core.ui.components.QuestuaTextField
import com.questua.app.domain.model.CharacterEntity
import com.questua.app.domain.model.Persona
import com.questua.app.domain.model.SpriteSheet
import com.questua.app.presentation.admin.content.dialogues.ExpandableListSection
import com.questua.app.presentation.admin.content.dialogues.SectionTitle
import java.io.File

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CharacterFormDialog(
    character: CharacterEntity? = null,
    onDismiss: () -> Unit,
    onConfirm: (
        name: String, avatar: Any?, voice: Any?,
        sprites: List<Any>, // Lista mista de String (URL existente) ou File (Novo upload)
        persona: Persona?, isAi: Boolean
    ) -> Unit
) {
    val context = LocalContext.current

    // Básico
    var name by remember { mutableStateOf(character?.name ?: "") }
    var isAiGenerated by remember { mutableStateOf(character?.isAiGenerated ?: false) }

    // Mídia (Any? pode ser String(Url) ou File)
    var avatar by remember { mutableStateOf<Any?>(character?.avatarUrl) }
    var voice by remember { mutableStateOf<Any?>(character?.voiceUrl) }

    // SpriteSheet (Lista mista)
    val spriteUrls = remember { mutableStateListOf<Any>().apply { addAll(character?.spriteSheet?.urls ?: emptyList()) } }

    // Persona
    var pDesc by remember { mutableStateOf(character?.persona?.description ?: "") }
    var pStyle by remember { mutableStateOf(character?.persona?.speakingStyle ?: "") }
    var pTone by remember { mutableStateOf(character?.persona?.voiceTone ?: "") }
    var pBack by remember { mutableStateOf(character?.persona?.background ?: "") }
    val pTraits = remember { mutableStateListOf<String>().apply { addAll(character?.persona?.traits ?: emptyList()) } }

    // Launchers
    val avatarPicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let { avatar = URIPathHelper.getFileFromUri(context, it) }
    }
    val voicePicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let { voice = URIPathHelper.getFileFromUri(context, it) }
    }
    val spritePicker = rememberLauncherForActivityResult(ActivityResultContracts.GetContent()) { uri ->
        uri?.let { URIPathHelper.getFileFromUri(context, it)?.let { file -> spriteUrls.add(file) } }
    }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text(if (character == null) "Novo Personagem" else "Editar Personagem") },
        text = {
            Column(
                Modifier.fillMaxWidth().verticalScroll(rememberScrollState()),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                // --- INFO BÁSICA ---
                QuestuaTextField(value = name, onValueChange = { name = it }, label = "Nome do Personagem")

                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = isAiGenerated, onCheckedChange = { isAiGenerated = it })
                    Text("Gerado por IA")
                }

                // --- ASSETS ---
                SectionTitle("Assets & Mídia")

                // Avatar
                Row(Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
                    Button(onClick = { avatarPicker.launch("image/*") }, Modifier.weight(1f)) {
                        Icon(Icons.Default.Upload, null); Spacer(Modifier.width(8.dp))
                        Text(if(avatar is File) "Avatar (Novo)" else if (avatar != null) "Avatar (OK)" else "Upload Avatar")
                    }
                }

                // Voice
                Row(Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
                    Button(onClick = { voicePicker.launch("audio/*") }, Modifier.weight(1f)) {
                        Icon(Icons.Default.Upload, null); Spacer(Modifier.width(8.dp))
                        Text(if(voice is File) "Voz (Novo)" else if (voice != null) "Voz (OK)" else "Upload Voz (Opcional)")
                    }
                    if (voice != null) {
                        IconButton(onClick = { voice = null }) { Icon(Icons.Default.Delete, "Remover voz") }
                    }
                }

                // Sprite Sheet List
                ExpandableListSection(title = "Sprite Sheet (${spriteUrls.size})", onAdd = { spritePicker.launch("image/*") }) {
                    spriteUrls.forEachIndexed { index, item ->
                        Row(
                            Modifier.fillMaxWidth().padding(4.dp).border(1.dp, MaterialTheme.colorScheme.outline, RoundedCornerShape(4.dp)).padding(8.dp),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(
                                if(item is File) "Arquivo: ${item.name.take(15)}..." else "URL: ${(item as String).takeLast(15)}",
                                style = MaterialTheme.typography.bodySmall,
                                modifier = Modifier.weight(1f)
                            )
                            IconButton(onClick = { spriteUrls.removeAt(index) }, modifier = Modifier.size(24.dp)) {
                                Icon(Icons.Default.Delete, null)
                            }
                        }
                    }
                }

                HorizontalDivider()

                // --- PERSONA ---
                SectionTitle("Persona")
                QuestuaTextField(value = pDesc, onValueChange = { pDesc = it }, label = "Descrição")
                QuestuaTextField(value = pBack, onValueChange = { pBack = it }, label = "Background / História")

                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    QuestuaTextField(value = pStyle, onValueChange = { pStyle = it }, label = "Estilo de Fala", modifier = Modifier.weight(1f))
                    QuestuaTextField(value = pTone, onValueChange = { pTone = it }, label = "Tom de Voz", modifier = Modifier.weight(1f))
                }

                // Traits List
                ExpandableListSection(title = "Traços de Personalidade (${pTraits.size})", onAdd = { pTraits.add("") }) {
                    pTraits.forEachIndexed { index, trait ->
                        Row(Modifier.padding(vertical = 4.dp), verticalAlignment = Alignment.CenterVertically) {
                            QuestuaTextField(value = trait, onValueChange = { pTraits[index] = it }, label = "Traço ${index + 1}", modifier = Modifier.weight(1f))
                            IconButton(onClick = { pTraits.removeAt(index) }) { Icon(Icons.Default.Delete, null) }
                        }
                    }
                }
            }
        },
        confirmButton = {
            Button(
                onClick = {
                    val finalPersona = if (pDesc.isBlank() && pTraits.isEmpty()) null else Persona(
                        description = pDesc.ifBlank { null },
                        traits = pTraits.filter { it.isNotBlank() },
                        speakingStyle = pStyle.ifBlank { null },
                        voiceTone = pTone.ifBlank { null },
                        background = pBack.ifBlank { null }
                    )

                    onConfirm(name, avatar, voice, spriteUrls, finalPersona, isAiGenerated)
                },
                enabled = name.isNotBlank() && (avatar != null) // Avatar é obrigatório no modelo
            ) { Text("Salvar") }
        },
        dismissButton = { TextButton(onClick = onDismiss) { Text("Cancelar") } }
    )
}