package com.questua.app.presentation.admin.content.quests

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.questua.app.core.ui.components.QuestuaTextField
import com.questua.app.domain.model.LearningFocus
import com.questua.app.domain.model.Quest
import com.questua.app.domain.model.QuestPoint
import com.questua.app.domain.model.SceneDialogue
import com.questua.app.domain.model.UnlockRequirement

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun QuestFormDialog(
    quest: Quest? = null,
    questPoints: List<QuestPoint>,
    dialogues: List<SceneDialogue>, // Para selecionar o primeiro diálogo
    onDismiss: () -> Unit,
    onConfirm: (
        title: String, qpId: String, dialId: String?, desc: String,
        diff: Int, order: Int, xp: Int,
        unlock: UnlockRequirement?, focus: LearningFocus?,
        prem: Boolean, ai: Boolean, pub: Boolean
    ) -> Unit
) {
    // Estados Básicos
    var title by remember { mutableStateOf(quest?.title ?: "") }
    var description by remember { mutableStateOf(quest?.description ?: "") }
    var questPointId by remember { mutableStateOf(quest?.questPointId ?: "") }
    var firstDialogueId by remember { mutableStateOf(quest?.firstDialogueId ?: "") }

    // Numéricos
    var difficulty by remember { mutableStateOf(quest?.difficulty?.toFloat() ?: 1f) }
    var orderIndex by remember { mutableStateOf(quest?.orderIndex?.toString() ?: "1") }
    var xpValue by remember { mutableStateOf(quest?.xpValue?.toString() ?: "100") }

    // Learning Focus (Comma Separated)
    var grammar by remember { mutableStateOf(quest?.learningFocus?.grammarTopics?.joinToString(", ") ?: "") }
    var vocabulary by remember { mutableStateOf(quest?.learningFocus?.vocabularyThemes?.joinToString(", ") ?: "") }
    var skills by remember { mutableStateOf(quest?.learningFocus?.skills?.joinToString(", ") ?: "") }

    // Flags
    var isPremium by remember { mutableStateOf(quest?.isPremium ?: false) }
    var isPublished by remember { mutableStateOf(quest?.isPublished ?: true) }
    var isAiGenerated by remember { mutableStateOf(quest?.isAiGenerated ?: false) }

    // Requisitos de Desbloqueio
    var reqPremium by remember { mutableStateOf(quest?.unlockRequirement?.premiumAccess ?: false) }
    var reqLevel by remember { mutableStateOf(quest?.unlockRequirement?.requiredGamificationLevel?.toString() ?: "") }
    var reqCefr by remember { mutableStateOf(quest?.unlockRequirement?.requiredCefrLevel ?: "") }

    // Controle de Menus
    var showQpPicker by remember { mutableStateOf(false) }
    var showDialoguePicker by remember { mutableStateOf(false) }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text(if (quest == null) "Nova Quest" else "Editar Quest") },
        text = {
            Column(
                Modifier.fillMaxWidth().verticalScroll(rememberScrollState()),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                QuestuaTextField(value = title, onValueChange = { title = it }, label = "Título")

                // SELETOR QUEST POINT (Obrigatório)
                OutlinedCard(onClick = { showQpPicker = true }) {
                    val current = questPoints.find { it.id == questPointId }
                    ListItem(
                        headlineContent = { Text(current?.title ?: "Selecionar Quest Point") },
                        supportingContent = { Text(if(questPointId.isEmpty()) "Obrigatório" else "ID: ...${questPointId.takeLast(8)}") },
                        colors = ListItemDefaults.colors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
                    )
                }

                // SELETOR DIÁLOGO INICIAL (Opcional)
                OutlinedCard(onClick = { showDialoguePicker = true }) {
                    val current = dialogues.find { it.id == firstDialogueId }
                    ListItem(
                        headlineContent = { Text(current?.textContent?.take(30)?.plus("...") ?: "Selecionar Diálogo Inicial") },
                        supportingContent = { Text(if(firstDialogueId.isEmpty()) "Opcional (Nenhum)" else "ID: ...${firstDialogueId.takeLast(8)}") },
                        colors = ListItemDefaults.colors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
                    )
                }

                QuestuaTextField(value = description, onValueChange = { description = it }, label = "Descrição")

                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    QuestuaTextField(value = orderIndex, onValueChange = { orderIndex = it }, label = "Ordem", modifier = Modifier.weight(1f))
                    QuestuaTextField(value = xpValue, onValueChange = { xpValue = it }, label = "XP", modifier = Modifier.weight(1f))
                }

                Column {
                    Text("Dificuldade: ${difficulty.toInt()}", style = MaterialTheme.typography.labelMedium)
                    Slider(value = difficulty, onValueChange = { difficulty = it }, valueRange = 1f..5f, steps = 3)
                }

                HorizontalDivider()
                Text("Foco de Aprendizado (Separe por vírgula)", style = MaterialTheme.typography.titleSmall, fontWeight = FontWeight.Bold)
                QuestuaTextField(value = grammar, onValueChange = { grammar = it }, label = "Gramática (ex: Verbos, Past Tense)")
                QuestuaTextField(value = vocabulary, onValueChange = { vocabulary = it }, label = "Vocabulário (ex: Viagem, Comida)")
                QuestuaTextField(value = skills, onValueChange = { skills = it }, label = "Habilidades (ex: Listening, Reading)")

                HorizontalDivider()
                Text("Requisitos de Desbloqueio", style = MaterialTheme.typography.titleSmall, fontWeight = FontWeight.Bold)
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = reqPremium, onCheckedChange = { reqPremium = it })
                    Text("Exigir Premium")
                }
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    QuestuaTextField(value = reqLevel, onValueChange = { reqLevel = it }, label = "Nível Min.", modifier = Modifier.weight(1f))
                    QuestuaTextField(value = reqCefr, onValueChange = { reqCefr = it }, label = "CEFR", modifier = Modifier.weight(1f))
                }

                HorizontalDivider()
                Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.SpaceBetween, modifier = Modifier.fillMaxWidth()) {
                    Row(verticalAlignment = Alignment.CenterVertically) { Checkbox(checked = isPublished, onCheckedChange = { isPublished = it }); Text("Publicado") }
                    Row(verticalAlignment = Alignment.CenterVertically) { Checkbox(checked = isPremium, onCheckedChange = { isPremium = it }); Text("Premium") }
                }
            }
        },
        confirmButton = {
            Button(
                onClick = {
                    val unlock = UnlockRequirement(
                        premiumAccess = reqPremium,
                        requiredGamificationLevel = reqLevel.toIntOrNull(),
                        requiredCefrLevel = reqCefr.ifEmpty { null }
                    )

                    val focus = LearningFocus(
                        grammarTopics = grammar.split(",").map { it.trim() }.filter { it.isNotEmpty() }.ifEmpty { null },
                        vocabularyThemes = vocabulary.split(",").map { it.trim() }.filter { it.isNotEmpty() }.ifEmpty { null },
                        skills = skills.split(",").map { it.trim() }.filter { it.isNotEmpty() }.ifEmpty { null }
                    )

                    onConfirm(
                        title, questPointId, firstDialogueId.ifEmpty { null }, description,
                        difficulty.toInt(), orderIndex.toIntOrNull() ?: 1, xpValue.toIntOrNull() ?: 0,
                        unlock, focus, isPremium, isAiGenerated, isPublished
                    )
                },
                enabled = title.isNotBlank() && questPointId.isNotBlank()
            ) { Text("Confirmar") }
        },
        dismissButton = { TextButton(onClick = onDismiss) { Text("Cancelar") } }
    )

    // Dialogs de Seleção
    if (showQpPicker) {
        SelectorDialog(
            title = "Selecione o Quest Point",
            items = questPoints,
            itemContent = { qp -> Text(qp.title, fontWeight = FontWeight.Bold); Text(qp.id, style = MaterialTheme.typography.bodySmall) },
            onSelect = { questPointId = it.id; showQpPicker = false },
            onDismiss = { showQpPicker = false }
        )
    }

    if (showDialoguePicker) {
        SelectorDialog(
            title = "Selecione o Diálogo Inicial",
            items = dialogues,
            itemContent = { d -> Text(d.textContent.take(50), fontWeight = FontWeight.Bold); Text(d.id, style = MaterialTheme.typography.bodySmall) },
            onSelect = { firstDialogueId = it.id; showDialoguePicker = false },
            onDismiss = { showDialoguePicker = false },
            canClear = true,
            onClear = { firstDialogueId = ""; showDialoguePicker = false }
        )
    }
}

@Composable
fun <T> SelectorDialog(
    title: String,
    items: List<T>,
    itemContent: @Composable (T) -> Unit,
    onSelect: (T) -> Unit,
    onDismiss: () -> Unit,
    canClear: Boolean = false,
    onClear: () -> Unit = {}
) {
    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text(title) },
        text = {
            Box(Modifier.heightIn(max = 400.dp)) {
                LazyColumn {
                    if (canClear) {
                        item {
                            ListItem(
                                modifier = Modifier.clickable { onClear() },
                                headlineContent = { Text("Nenhum (Remover Seleção)", color = MaterialTheme.colorScheme.error) }
                            )
                            HorizontalDivider()
                        }
                    }
                    items(items) { item ->
                        ListItem(
                            modifier = Modifier.clickable { onSelect(item) },
                            headlineContent = { itemContent(item) }
                        )
                        HorizontalDivider()
                    }
                }
            }
        },
        confirmButton = { TextButton(onClick = onDismiss) { Text("Fechar") } }
    )
}