package com.questua.app.presentation.admin.content.dialogues

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.questua.app.core.ui.components.QuestuaTextField
import com.questua.app.domain.enums.InputMode
import com.questua.app.domain.model.*
import com.questua.app.presentation.admin.content.quests.SelectorDialog // Reutilizando do passo anterior

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SceneDialogueFormDialog(
    dialogue: SceneDialogue? = null,
    characters: List<CharacterEntity>,
    allDialogues: List<SceneDialogue>,
    onDismiss: () -> Unit,
    onConfirm: (
        txt: String, desc: String, bg: String, music: String?,
        states: List<CharacterState>?, effects: List<SceneEffect>?,
        speaker: String?, audio: String?, expects: Boolean,
        mode: InputMode, expectResp: String?, choices: List<Choice>?,
        next: String?, ai: Boolean
    ) -> Unit
) {
    // Campos Básicos
    var description by remember { mutableStateOf(dialogue?.description ?: "") }
    var textContent by remember { mutableStateOf(dialogue?.textContent ?: "") }
    var backgroundUrl by remember { mutableStateOf(dialogue?.backgroundUrl ?: "") }
    var bgMusicUrl by remember { mutableStateOf(dialogue?.bgMusicUrl ?: "") }
    var audioUrl by remember { mutableStateOf(dialogue?.audioUrl ?: "") }
    var speakerId by remember { mutableStateOf(dialogue?.speakerCharacterId ?: "") }
    var nextDialogueId by remember { mutableStateOf(dialogue?.nextDialogueId ?: "") }

    // Configurações
    var inputMode by remember { mutableStateOf(dialogue?.inputMode ?: InputMode.NONE) }
    var expectsUserResponse by remember { mutableStateOf(dialogue?.expectsUserResponse ?: false) }
    var expectedResponse by remember { mutableStateOf(dialogue?.expectedResponse ?: "") }
    var isAiGenerated by remember { mutableStateOf(dialogue?.isAiGenerated ?: false) }

    // Listas Complexas (State Management)
    val characterStates = remember { mutableStateListOf<CharacterState>().apply { addAll(dialogue?.characterStates ?: emptyList()) } }
    val sceneEffects = remember { mutableStateListOf<SceneEffect>().apply { addAll(dialogue?.sceneEffects ?: emptyList()) } }
    val choices = remember { mutableStateListOf<Choice>().apply { addAll(dialogue?.choices ?: emptyList()) } }

    // Seletores
    var showSpeakerPicker by remember { mutableStateOf(false) }
    var showNextDialogPicker by remember { mutableStateOf(false) }
    var showModePicker by remember { mutableStateOf(false) }

    // Auxiliares para itens de lista
    var showStateCharPicker by remember { mutableStateOf<Int?>(null) } // Index do item sendo editado
    var showChoiceDialogPicker by remember { mutableStateOf<Int?>(null) } // Index do item sendo editado

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text(if (dialogue == null) "Novo Diálogo" else "Editar Diálogo") },
        text = {
            Column(
                Modifier.fillMaxWidth().verticalScroll(rememberScrollState()),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                // --- BÁSICO ---
                SectionTitle("Informações Básicas")
                QuestuaTextField(value = description, onValueChange = { description = it }, label = "Descrição Interna")
                QuestuaTextField(value = textContent, onValueChange = { textContent = it }, label = "Texto do Diálogo")

                // --- MÍDIA ---
                SectionTitle("Mídia & Ambiente")
                QuestuaTextField(value = backgroundUrl, onValueChange = { backgroundUrl = it }, label = "URL Fundo")
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    QuestuaTextField(value = bgMusicUrl, onValueChange = { bgMusicUrl = it }, label = "URL Música", modifier = Modifier.weight(1f))
                    QuestuaTextField(value = audioUrl, onValueChange = { audioUrl = it }, label = "URL Áudio (Fala)", modifier = Modifier.weight(1f))
                }

                // --- ATORES ---
                SectionTitle("Quem Fala?")
                OutlinedCard(onClick = { showSpeakerPicker = true }) {
                    val current = characters.find { it.id == speakerId }
                    ListItem(
                        headlineContent = { Text(current?.name ?: "Narrador / Nenhum") },
                        supportingContent = { Text(if(speakerId.isEmpty()) "Opcional" else "ID: ...${speakerId.takeLast(8)}") }
                    )
                }

                // --- FLUXO ---
                SectionTitle("Fluxo & Interação")
                OutlinedCard(onClick = { showModePicker = true }) {
                    ListItem(headlineContent = { Text("Modo de Entrada: ${inputMode.name}") })
                }

                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = expectsUserResponse, onCheckedChange = { expectsUserResponse = it })
                    Text("Aguarda Resposta do Usuário")
                }

                if (expectsUserResponse) {
                    QuestuaTextField(value = expectedResponse, onValueChange = { expectedResponse = it }, label = "Resposta Esperada (Opcional)")
                }

                OutlinedCard(onClick = { showNextDialogPicker = true }) {
                    val current = allDialogues.find { it.id == nextDialogueId }
                    ListItem(
                        headlineContent = { Text(current?.textContent?.take(30)?.plus("...") ?: "Fim da Cena / Nenhum") },
                        supportingContent = { Text("Próximo Diálogo (ID: ...${nextDialogueId.takeLast(8)})") }
                    )
                }

                // --- LISTAS COMPLEXAS ---

                // 1. Character States
                ExpandableListSection(title = "Estados dos Personagens (${characterStates.size})", onAdd = { characterStates.add(CharacterState("", "", "")) }) {
                    characterStates.forEachIndexed { index, state ->
                        Column(Modifier.padding(8.dp).border(1.dp, MaterialTheme.colorScheme.outlineVariant, RoundedCornerShape(8.dp)).padding(8.dp)) {
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Text("Personagem", style = MaterialTheme.typography.labelSmall)
                                Spacer(Modifier.weight(1f))
                                IconButton(onClick = { characterStates.removeAt(index) }, modifier = Modifier.size(24.dp)) { Icon(Icons.Default.Delete, null) }
                            }
                            OutlinedCard(onClick = { showStateCharPicker = index }) {
                                val name = characters.find { it.id == state.characterId }?.name ?: "Selecionar..."
                                Text(name, Modifier.padding(8.dp))
                            }
                            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                                QuestuaTextField(value = state.expression ?: "", onValueChange = { characterStates[index] = state.copy(expression = it) }, label = "Expressão", modifier = Modifier.weight(1f))
                                QuestuaTextField(value = state.position ?: "", onValueChange = { characterStates[index] = state.copy(position = it) }, label = "Posição", modifier = Modifier.weight(1f))
                            }
                        }
                    }
                }

                // 2. Choices
                ExpandableListSection(title = "Opções de Escolha (${choices.size})", onAdd = { choices.add(Choice("", null)) }) {
                    choices.forEachIndexed { index, choice ->
                        Column(Modifier.padding(8.dp).border(1.dp, MaterialTheme.colorScheme.outlineVariant, RoundedCornerShape(8.dp)).padding(8.dp)) {
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Text("Texto da Escolha", style = MaterialTheme.typography.labelSmall)
                                Spacer(Modifier.weight(1f))
                                IconButton(onClick = { choices.removeAt(index) }, modifier = Modifier.size(24.dp)) { Icon(Icons.Default.Delete, null) }
                            }
                            QuestuaTextField(value = choice.text, onValueChange = { choices[index] = choice.copy(text = it) }, label = "")

                            OutlinedCard(onClick = { showChoiceDialogPicker = index }) {
                                val nextName = allDialogues.find { it.id == choice.nextDialogueId }?.textContent?.take(20) ?: "Nenhum"
                                Text("Vai para: $nextName", Modifier.padding(8.dp))
                            }
                        }
                    }
                }

                // 3. Effects
                ExpandableListSection(title = "Efeitos de Cena (${sceneEffects.size})", onAdd = { sceneEffects.add(SceneEffect("SHAKE", 1.0, 1.0, null)) }) {
                    sceneEffects.forEachIndexed { index, effect ->
                        Column(Modifier.padding(8.dp).border(1.dp, MaterialTheme.colorScheme.outlineVariant, RoundedCornerShape(8.dp)).padding(8.dp)) {
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Text("Tipo", style = MaterialTheme.typography.labelSmall)
                                Spacer(Modifier.weight(1f))
                                IconButton(onClick = { sceneEffects.removeAt(index) }, modifier = Modifier.size(24.dp)) { Icon(Icons.Default.Delete, null) }
                            }
                            QuestuaTextField(value = effect.type, onValueChange = { sceneEffects[index] = effect.copy(type = it) }, label = "Ex: SHAKE, FADE")
                            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                                QuestuaTextField(value = effect.intensity?.toString() ?: "", onValueChange = { sceneEffects[index] = effect.copy(intensity = it.toDoubleOrNull()) }, label = "Intensidade", modifier = Modifier.weight(1f))
                                QuestuaTextField(value = effect.duration?.toString() ?: "", onValueChange = { sceneEffects[index] = effect.copy(duration = it.toDoubleOrNull()) }, label = "Duração", modifier = Modifier.weight(1f))
                            }
                        }
                    }
                }
            }
        },
        confirmButton = {
            Button(onClick = {
                onConfirm(
                    textContent, description, backgroundUrl, bgMusicUrl.ifEmpty { null },
                    characterStates.ifEmpty { null }, sceneEffects.ifEmpty { null },
                    speakerId.ifEmpty { null }, audioUrl.ifEmpty { null },
                    expectsUserResponse, inputMode, expectedResponse.ifEmpty { null },
                    choices.ifEmpty { null }, nextDialogueId.ifEmpty { null }, isAiGenerated
                )
            }) { Text("Salvar") }
        },
        dismissButton = { TextButton(onClick = onDismiss) { Text("Cancelar") } }
    )

    // --- SELETORES ---

    if (showSpeakerPicker) {
        SelectorDialog("Selecione quem fala", characters, { Text(it.name) }, { speakerId = it.id; showSpeakerPicker = false }, { showSpeakerPicker = false }, true, { speakerId = ""; showSpeakerPicker = false })
    }

    if (showNextDialogPicker) {
        SelectorDialog("Próximo Diálogo", allDialogues, { Text(it.textContent.take(50)) }, { nextDialogueId = it.id; showNextDialogPicker = false }, { showNextDialogPicker = false }, true, { nextDialogueId = ""; showNextDialogPicker = false })
    }

    if (showModePicker) {
        AlertDialog(
            onDismissRequest = { showModePicker = false },
            title = { Text("Modo de Entrada") },
            text = {
                Column {
                    InputMode.values().forEach { mode ->
                        ListItem(
                            modifier = Modifier.clickable { inputMode = mode; showModePicker = false },
                            headlineContent = { Text(mode.name) }
                        )
                    }
                }
            },
            confirmButton = {}
        )
    }

    // Seletores de Lista
    showStateCharPicker?.let { idx ->
        SelectorDialog("Selecione Personagem", characters, { Text(it.name) }, {
            val old = characterStates[idx]
            characterStates[idx] = old.copy(characterId = it.id)
            showStateCharPicker = null
        }, { showStateCharPicker = null })
    }

    showChoiceDialogPicker?.let { idx ->
        SelectorDialog("Destino da Escolha", allDialogues, { Text(it.textContent.take(50)) }, {
            val old = choices[idx]
            choices[idx] = old.copy(nextDialogueId = it.id)
            showChoiceDialogPicker = null
        }, { showChoiceDialogPicker = null }, true, {
            val old = choices[idx]
            choices[idx] = old.copy(nextDialogueId = null)
            showChoiceDialogPicker = null
        })
    }
}

@Composable
fun SectionTitle(title: String) {
    Text(title, style = MaterialTheme.typography.titleSmall, fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.primary, modifier = Modifier.padding(top = 8.dp))
}

@Composable
fun ExpandableListSection(title: String, onAdd: () -> Unit, content: @Composable () -> Unit) {
    var expanded by remember { mutableStateOf(false) }
    Column(Modifier.fillMaxWidth().background(MaterialTheme.colorScheme.surfaceVariant.copy(alpha=0.3f), RoundedCornerShape(8.dp)).padding(8.dp)) {
        Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.clickable { expanded = !expanded }) {
            Text(title, style = MaterialTheme.typography.titleSmall, fontWeight = FontWeight.Bold)
            Spacer(Modifier.weight(1f))
            if(expanded) IconButton(onClick = onAdd, modifier = Modifier.size(24.dp)) { Icon(Icons.Default.Add, null) }
        }
        if (expanded) {
            Spacer(Modifier.height(8.dp))
            content()
        }
    }
}